name: main

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'hotfix'
      - 'hotfix/**'
      - 'master'

jobs:
  check:
    name: Check for skipping
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check1.num-changes > 0 }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check changes.
        id: check1
        shell: bash
        run: echo ::set-output name=num-changes::$(make check-changes)

      - name: Number of files changed
        shell: bash
        run: echo "${{ steps.check1.num-changes }}"

      - name: Number of files changed (2)
        shell: bash
        run: git diff --exit-code --name-only HEAD HEAD~1

      - name: Number of files changed (2)
        shell: bash
        run: make check-changes


  build:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.changed

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Lint
        shell: bash
        run: make lint

      - name: Test
        shell: bash
        run: make test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: target

      - name: Slack Status on Error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }}` triggered by `${{ github.event_name }}` failed\n\n:arrow_right:<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,action
        if: ${{ failure() }}


  deploy:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Bump Snapshot
        shell: bash
        run: make bump-snapshot-and-push

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::$(make version)

      - name: Package
        shell: bash
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.version }}.jar
          path: output/assembly.jar

      - name: Deploy to Dev
        shell: bash
        run: make deploy-to-dev

      - name: Deploy notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields:
          text: ":rocket: *${{ github.event.repository.name }} v${{ steps.vars.outputs.version }}* deployed to *DEV*\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions?query=workflow%3Arelease|Start Release Workflow>"


      - name: Slack Status on Error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }}` triggered by `${{ github.event_name }}` failed\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,action
        if: ${{ failure() }}



