name: release

on:
  workflow_dispatch:

jobs:
  release-deploy:
    name: Build Release & Deploy to Staging
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/hotfix'

    steps:
      - name: Delete current release branch
        uses: dawidd6/action-delete-branch@v3
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        with:
          github_token: ${{github.token}}
          branches: release

      - name: Create new release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'

      - name: Check out repository code
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/master'
        with:
          ref: 'release'
          fetch-depth: 0

      - name: Check out repository code
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/hotfix'
        with:
          ref: 'hotfix'
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Bump Release
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: make bump-release-and-push

      - name: Bump Hotfix
        if: github.ref == 'refs/heads/hotfix'
        shell: bash
        run: make bump-patch-and-push

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::$(make version)

      - name: Create PR
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release
          destination_branch: master
          pr_title: "Release ${{ steps.vars.outputs.version }} to PROD"
          pr_body: ":crown: *An automated PR*\nWhen merged ${{ github.event.repository.name }} ${{ steps.vars.outputs.version }} will be released to PROD"
          pr_reviewer: "${{ github.repository_owner	}},${{ github.actor	}}"
          pr_assignee: "${{ github.repository_owner	}}"
          pr_label: "auto-pr,release"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        shell: bash
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.version }}.jar
          path: output/assembly.jar

      - name: Deploy to Staging
        shell: bash
        run: make deploy-to-staging

      - name: Deploy notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields:
          text: ":rocket: *${{ github.event.repository.name }} v${{ steps.vars.outputs.version }}* deployed to *STAGING*\n\n:arrow_right: <${{ steps.pr.outputs.pr_url}}|Release To PROD>"

      - name: Slack Status on Error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }}` triggered by `${{ github.event_name }}` failed\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,action
        if: ${{ failure() }}


