name: release

on:
  workflow_dispatch:

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Delete current release branch
        uses: dawidd6/action-delete-branch@v3
        continue-on-error: true
        with:
          github_token: ${{github.token}}
          branches: release

      - name: Create new release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'release'
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Bump Release
        shell: bash
        run: make bump-release-and-push

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::$(make version)

      - name: Package
        shell: bash
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: scala-github-actions-${{ steps.vars.outputs.version }}.jar
          path: output/assembly.jar

      - name: Deploy to Staging
        shell: bash
        run: make deploy-to-staging

      - name: Deploy notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields:
          text: ':rocket: v${{ steps.vars.outputs.version }} deployed to STAGING'
          custom_payload: |
            {
              attachments: [{
                actions: [{
                  {
                    "name": "game",
                    "url": "https://github.com/TomLous/scala-github-actions",
                    "text": "Release to Prod",
                    "type": "button",
                    "style": "primary"
                  }
                }]
              }]
            }

      - name: Slack Status on Error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields: repo,message,commit,action
        if: ${{ failure() }}


