name: release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'major or minor?'
        required: true
        default: 'minor'

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Delete current release branch
        uses: dawidd6/action-delete-branch@v3
        continue-on-error: true
        with:
          github_token: ${{github.token}}
          branches: release

      - name: Create new release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'release'
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Github config
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"


