name: 'Manual: Start release'

on:
  workflow_dispatch:

jobs:
  release-deploy:
    name:  Build & Deploy to Staging
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/hotfix'

    steps:
      - name: Set release type
        id: type
        run: |
          if [ "$REF" == "refs/heads/master" ]
          then
              echo "::set-output name=branch::release"
          else
              echo "::set-output name=branch::hotfix"
          fi
        env:
          REF: ${{ github.ref }}

      - name: Delete current release branch
        uses: dawidd6/action-delete-branch@v3
        if: steps.type.outputs.branch == 'release'
        continue-on-error: true
        with:
          github_token: ${{github.token}}
          branches: release

      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        if: steps.type.outputs.branch == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.type.outputs.branch }}
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Bump Release
        if: steps.type.outputs.branch == 'release'
        shell: bash
        run: make bump-release-and-push

      - name: Bump Hotfix
        if: steps.type.outputs.branch == 'hotfix'
        shell: bash
        run: make bump-patch-and-push

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::$(make version)

      - name: Find old PR
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.type.outputs.branch }}

      - name: Close old PR
        if: ${{ steps.find-pull-request.outputs.number > 0 }}
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
          comment: Auto-closing pull request
          delete-branch: false

      - name: Create new PR
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.type.outputs.branch }}
          destination_branch: master
          pr_title: "Release ${{ steps.vars.outputs.version }} to PROD"
          pr_body: ":gear: *Automated PR*\nWhen merged ${{ github.event.repository.name }} ${{ steps.vars.outputs.version }} ${{ steps.type.outputs.branch }} will be released to PROD\nClose PR to cancel"
          pr_reviewer: "${{ github.repository_owner	}},${{ github.actor	}}"
          pr_assignee: "${{ github.repository_owner	}}"
          pr_label: "auto-pr,release"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package code
        shell: bash
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.version }}.jar
          path: output/assembly.jar

      - name: Deploy to STAGING
        shell: bash
        run: make deploy-to-staging

      - name: Deploy notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields:
          text: ":rocket: ${{ github.event.repository.name }} *v${{ steps.vars.outputs.version }}* deployed to *STAGING*\n\n:arrow_right: <${{ steps.pr.outputs.pr_url}}|Release To PROD>"

      - name: Slack on error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }}` triggered by `${{ github.event_name }}` failed\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,action
        if: ${{ failure() }}


